
## Recuperar Todos los Tours
GET http://localhost:4888/Tours

### Recuperar un Tour por id
GET http://localhost:4888/Tours/4fd6bc33-9407-4d5f-a16b-e183f61f76dd

### Recuperar Los Tours por Location
GET http://localhost:4888/Tours?location=France

### create a New Tour
POST http://localhost:4888/Tours
Content-Type: application/json

{
    "id": 31,
        "src": "images/img-54.jpg",
        "text": "Explore The City of Brucelas",
        "label": "Family",
        "price": "$950",
        "location": "Belgium"
}

### Borrar un Tour
DELETE http://localhost:4888/Tours

### Actualizar un Tour
PATCH http://localhost:4888/Tours
Content-Type: application/json

{
  "price": "1500$"
}



